var config={startSoundValue:30,percentLoadingSpeed:20,percentLoadingTime:2000,playingSpeed:3000,bufferingSpeed:30000,openingSceneSpeed:5000,autoplay:false};var movie_year;$(document).ready(function(ev){$(".slider").slider({range:'min',value:config.startSoundValue});makeRandoms();findContent();});function makeRandoms(){document.getElementById("media-likes-facebook").innerHTML=randomize(6)+" M";document.getElementById("media-likes-googleplus").innerHTML=randomize(3)+" M";document.getElementById("media-likes-twitter").innerHTML=randomize(5)+" M";document.getElementById("random-number").innerHTML=randomize(12);}
function formatTitle(title){console.log(title);return title.split('Season')[0];}
function formatIDContent(content){console.log(content.id);if(content.media_type==="tv")
return content.id+"-"+content.original_name.replace(" ","-").toLowerCase();else if(content.media_type==="movie")
return content.id+"-"+content.original_title.replace(" ","-").toLowerCase();}
function formatTVSeason(){return params['title'].substring(params['title'].indexOf(' Season ')+8,params['title'].indexOf(', Episode '));}
function formatTVEpisode(){return params['title'].substring(params['title'].indexOf(', Episode ')+10,String(params['title'].length));}
function fillMovieData(movie){$.getJSON("https://api.themoviedb.org/3/movie/"+formatIDContent(movie)+"?api_key="+TemmovieApi,function(movie_full){$("#no-title").html(movie.original_title);$("#plot").html(movie.overview);$("#Title").html(movie.original_title);$('.overlay-movie-name').html(movie.original_title);$("#poster").attr("src","https://image.tmdb.org/t/p/w780/"+movie.poster_path);if(!config.autoplay){$('.overlay-video').css("background","url('https://image.tmdb.org/t/p/w780/"+movie.backdrop_path+"')");}
else{$('.play-button').trigger('click');}
$.getJSON("https://www.omdbapi.com/?i="+movie_full.imdb_id+"&plot=short&r=json&apikey=a7f1aba",function(result){$("#release").html(result.Released);$("#genre").html(result.Genre);$("#Director").html(result.Director);$("#actors").html(result.Actors);$("#Writer").html(result.Writer);$("#Language").html(result.Language);$("#Runtime").html(result.Runtime);$("#Country").html(result.Country);$(".length-2").html(result.Runtime);$('.length').html(Math.floor(parseInt(result.Runtime))+":"+randomize(59));$("#imdbRating").html(result.imdbRating);});});}
function fillTVData(tv){$.getJSON("https://api.themoviedb.org/3/tv/"
+formatIDContent(tv)
+"/season/"+formatTVSeason()
+"/episode/"+formatTVEpisode()
+"?api_key=48601496173843f8c0cb73f04d9b53bb",function(episode){var episode_title=tv.original_name+": Season "+formatTVSeason()+", Episode "+formatTVEpisode();$("#no-title").html(episode_title);$("#plot").html(episode.overview);$('.overlay-movie-name').html(episode_title);$("#Title").html(episode_title);$("#poster").attr("src","https://image.tmdb.org/t/p/w780/"+tv.poster_path);if(!config.autoplay){$('.overlay-video').css("background","url('https://image.tmdb.org/t/p/w780/"+tv.backdrop_path+"')");}
else{$('.play-button').trigger('click');}
$.getJSON("https://api.themoviedb.org/3/tv/"+formatIDContent(tv)+"/external_ids?api_key="+TemmovieApi,function(tv_ids){$.getJSON("https://www.omdbapi.com/?i="+tv_ids.imdb_id+"&plot=short&r=json&apikey=a7f1aba",function(result){$("#release").html(result.Released);$("#genre").html(result.Genre);$("#Director").html(result.Director);$("#actors").html(result.Actors);$("#Writer").html(result.Writer);$("#Language").html(result.Language);$("#Runtime").html(result.Runtime);$("#Country").html(result.Country);$(".length-2").html(result.Runtime);$('.length').html(Math.floor(parseInt(result.Runtime))+":"+randomize(59));$("#imdbRating").html(result.imdbRating);});});});}
console.log(params['title']);function findContent(){$.getJSON("https://api.themoviedb.org/3/search/multi?query="+formatTitle(params['title'])+"&api_key="+TemmovieApi,function(result){$('.overlay-image img').attr('src','https://image.tmdb.org/t/p/w780'+result.results[0].backdrop_path);if(result.results[0].media_type==="tv"){fillTVData(result.results[0]);}
else if(result.results[0].media_type==="movie")
fillMovieData(result.results[0]);else
console.log("Error: Not find content.");});}
function randomize(range){return Math.floor((Math.random()*range)+2);}
$('.play-button, .icon-play').on('click',function(){$('.play-button').hide();$('.icon-play').hide();$('.icon-pause').show();$('.overlay-video').fadeOut();$('.percent-container').show();var percent=0;setInterval(function(){$('.percent').html("Loading: "+percent+"%");percent++;},config.percentLoadingSpeed)
setTimeout(function(){$('.percent-container').hide();$('.time-full').animate({width:'1%'},config.playingSpeed);$('.time-buffer').animate({width:'50%'},config.bufferingSpeed);$('.opening-scene img').fadeIn(config.openingSceneSpeed,function(){$('.form-container').fadeIn();$(this).hide();});},config.percentLoadingTime);});var body=$('html, body');var darkOverlay=$('.dark-overlay');var overlayWindow=$('.overlay-padding');var overlayCloseBtn=$('html .overlay-close-button');var downloadBtn=$('.download-btn-wrap');var loginBtn=$('.login-btn');var loginError=$('.login-error-text');var logMeBtn=$('.log-me-button');var footerBtn=$('.footer-btn');var footerLogin=$('.footer-login');logMeBtn.on('click',function(evt){evt.preventDefault();loginError.show(200);setTimeout(function(){loginError.text('wrong username or password').css('width','185px');},4000)});overlayCloseBtn.on('click',function(){overlayWindow.animate({opacity:0},0).css({'top':'0','visibility':'hidden',paddingRight:'0'});loginError.hide().text('please wait...');setTimeout(function(){darkOverlay.animate({opacity:0},0).css('visibility','hidden');},200);body.toggleClass('no-scroll');$('.opening-scene img').hide();$('.opening-scene img').hide();$('html .form-container').fadeIn();});loginBtn.on('click',ToggleOverlay);footerLogin.on('click',ToggleOverlay);function ToggleOverlay(evt){evt.preventDefault();darkOverlay.animate({opacity:.7},200).css('visibility','visible');setTimeout(function(){overlayWindow.animate({opacity:1},0).css({'visibility':'visible','top':'50px',paddingRight:'17px'});},200);body.toggleClass('no-scroll');}